import { BOARD_PRESETS, U8G2_CONSTRUCTORS } from '../utils/constants';

export const generateDeviceCode = (framesData, config) => {
  const { fps, board, protocol, language } = config;
  const constructor = U8G2_CONSTRUCTORS[protocol];
  const includeLib = protocol === 'spi' ? '#include <SPI.h>' : '#include <Wire.h>';
  let code = '';

  if (language === 'cpp') {
    code = `/* * Generated by OLED Face Designer
 * Board target: ${BOARD_PRESETS[board].name}
 * Connections: ${BOARD_PRESETS[board][protocol]}
 */\n
#include <Arduino.h>
#include <U8g2lib.h>
${includeLib}\n
${constructor}\n
// Frame Data (1024 bytes per frame)\n`;

    framesData.forEach((data, i) => {
      code += `const uint8_t frame_${i}[] PROGMEM = {\n  ${data}\n};\n\n`;
    });

    code += `const uint8_t* const frames[] PROGMEM = { ${framesData.map((_, i) => `frame_${i}`).join(', ')} };
const int NUM_FRAMES = ${framesData.length};
int current_frame = 0;\n
void setup() {
  u8g2.begin();
}\n
void loop() {
  u8g2.clearBuffer();
  u8g2.drawXBMP(0, 0, 128, 64, frames[current_frame]);
  u8g2.sendBuffer();\n
  current_frame = (current_frame + 1) % NUM_FRAMES;
  delay(${Math.floor(1000 / fps)});
}\n`;

  } else if (language === 'micropython') {
    code = `# Generated by OLED Face Designer
# Board target: ${BOARD_PRESETS[board].name}
# Connections: ${BOARD_PRESETS[board][protocol]}\n
from machine import Pin, ${protocol === 'i2c' ? 'I2C' : 'SPI'}
import ssd1306
import framebuf
import time\n
# --- Setup Display ---\n`;

    if (protocol === 'i2c') {
      code += `i2c = I2C(0, scl=Pin(22), sda=Pin(21)) # Update I2C ID and Pins for your board\n`;
      code += `oled = ssd1306.SSD1306_I2C(128, 64, i2c)\n`;
    } else {
      code += `spi = SPI(1, baudrate=8000000, sck=Pin(18), mosi=Pin(23)) # Update SPI ID and Pins\n`;
      code += `oled = ssd1306.SSD1306_SPI(128, 64, spi, dc=Pin(2), res=Pin(4), cs=Pin(5))\n`;
    }

    code += `\n# --- Frame Data (1024 bytes per frame) ---\n`;
    framesData.forEach((data, i) => {
      code += `frame_${i} = bytearray([\n  ${data}\n])\n\n`;
    });

    code += `frames = [${framesData.map((_, i) => `frame_${i}`).join(', ')}]\n`;
    code += `num_frames = ${framesData.length}\n`;
    code += `fps_delay = ${+(1 / fps).toFixed(3)}\n\n`;
    code += `# --- Main Loop ---\ncurrent_frame = 0\nwhile True:\n`;
    code += `    # framebuf.MONO_HLSB matches XBMP format\n`;
    code += `    fb = framebuf.FrameBuffer(frames[current_frame], 128, 64, framebuf.MONO_HLSB)\n`;
    code += `    oled.fill(0)\n    oled.blit(fb, 0, 0)\n    oled.show()\n\n`;
    code += `    current_frame = (current_frame + 1) % num_frames\n    time.sleep(fps_delay)\n`;
  }

  return code;
};
